## 동기(Synchroonus)와 비동기(Asynchronous)

### 동기 처리

현재 실행 중인 작업이 종료할 때까지 다음에 실행될 작업이 대기하는 방식입니다.

예를 들어 작업 A를 하고 있다면 다음 작업 B는 작업 A가 끝날 때까지 기다려야합니다.

동기적으로 처리를 한다면 한 작업이 시간이 오래 걸린다면 다음 작업은 이를 기다리기 때문에 많은 시간과 비용이 나올 수 있는 단점이 있습니다.

### 비동기 처리

현재 실행 중인 작업이 종료되지 않은 상태라 해도 다음 작업이 곧바로 실행하는 방식입니다.

동기 처리와 달리 작업 A를 끝날 때 까지 기다리지않고 작업 B가 동시에 작업을 하는 것입니다. 작업 A는 끝나는 대로 결과 값을 출력하게 됩니다.

동기 처리와 달리 기다리지 않고 작업을 처리하기 때문에 시간과 비용적으로 동기 처리보다 이득을 볼 수 있습니다. 하지만 작업의 순서가 보장되지 않는 단점이 있습니다.

비동기 처리는 콜백 패턴을 많이 사용하는데 콜백 패턴은 콜백 헬에 빠지기 쉽고 가독성이 좋지 않습니다.
또한 콜백 패턴은 에러처리를 다루기 어려우며 여러개의 비동기 처리를 한번에 처리하는것이 어렵습니다. 이를 해결하기 위해서 프로미스, async/await을 사용하는 것이 좋습니다.

## 예시

### 동기 처리

```js
const a = (func, delay) => {
  console.log('a');
  const startTime = Date.now();

  while (Date.now() < startTime + delay);

  func();
};

const b = () => {
  console.log('b');
};

const c = () => {
  console.log('c');
};

const startTime = Date.now();
a(b, 300);
c();
const endTime = Date.now();
console.log(`${endTime - startTime}ms`);

/*
a
b
c
304ms
*/
```

a함수를 호출하면 "a"를 출력하고 300ms 후에 b 함수를 호출하여 "b"를 출력합니다., a함수가 종료되면 c함수를 호출하여 "c"를 출력합니다.

c함수는 a함수가 종료된 후에 호출되므로 300ms + a함수의 호출 시간(304ms) 이상 호출되지 못하고 블로킹이 되는 것을 의미합니다.

이 처럼 전의 작업을 기다리고 다음 작업을 처리하는 것을 동기 처리라고 합니다.

### 비동기 처리

위의 a함수를 setTimeout 함수를 사용하여 콜백함수로 b를 호출해 보겠습니다.

```js
const b = () => {
  console.log('delay 300ms');
  console.log('b');
};

const c = () => {
  console.log('c');
};

const startTime = Date.now();
// a(b, 300);
setTimeout(b, 300);
c();
const endTime = Date.now();
console.log(`${endTime - startTime}ms`);

/*
c
7ms
delay 300ms
b
*/
```

setTimeout 비동기 API 함수를 사용하였기 때문에 setTimeout 함수를 호출하면 해당 함수는 이를 처리하는 다른 프로그램에 맡기게 됩니다. 그렇기 때문에 "c"를 먼저 출력하고 300ms 이후 "b"를 출력합니다.

전 작업을 기다리지 않고 다음 작업을 실행 하는 이러한 처리를 비동기 처리라고 합니다.

## 콜백 함수로 비동기 처리 방식 해결

```jsx
const callbackFunc = params => {
  console.log(params);
};

const printFunc = callbackFunc => {
  let value;
  console.log('Waiting 3s');
  console.log('Waiting...');

  setTimeout(() => {
    value = 'Hello';
    callbackFunc(value);
  }, 3000);
};

printFunc(callbackFunc);
/* Start
Waiting 3s
Waiting...
(3s after)
Hello
End */
```

### 콜백 지옥 Callback hell

```jsx
const a = callback => {
  callback('callback');
};

const b = (result, callback) => {
  console.log(result);
  callback(result);
};
const c = (result, callback) => {
  console.log(result);
  callback(result);
};
const d = (result, callback) => {
  console.log(result);
  callback(result);
};
const e = (result, callback) => {
  console.log(result);
  callback(result);
};
const f = (result, callback) => {
  console.log(result);
  callback(result);
};

a(resultsFromA => {
  b(resultsFromA, resultsFromB => {
    c(resultsFromB, resultsFromC => {
      d(resultsFromC, resultsFromD => {
        e(resultsFromD, resultsFromE => {
          f(resultsFromE, resultsFromF => {
            console.log(resultsFromF);
          });
        });
      });
    });
  });
});
```

콜백함수의 극닥전인 예시이다. 위와 같은 코드는 가독성이 떨어지고 에러처리 등에서 불편하다.

이를 해소하기 위해 `ES6`에서 `Promise` 객체가 등장했다.

## Promise

Promise 개체는 비동기 작업의 최종 완료 (또는 실패)와 그 결과 값을 나타낸다.

Promise는 자바스크립트 비동기 처리에 사용되는 객체이다.

비동기 작업이 종료후 성공이나 실패를 처리할 수 있다.

[Promise - JavaScript | MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise#설명)

![https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/promises.png](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/promises.png)

Promise는 다음 중 하나의 상태를 가진다.

- 대기(pending): 이행하거나 거부되지 않은 초기 상태
- 이행(fulfilled): 연산이 성공적으로 완료됨
- 거부(rejected): 연산이 실패함

성공 시 fullfilled

```jsx
const promise = () =>
  new Promise((resolve, reject) => {
    console.log('pending'); //pending...
    resolve(`I'm resolve Fullfiled`);
  }).then(a => console.log(res));

promise(); // I'm resolve Fullfiled
```

실패시 rejected

```jsx
const promise = () =>
  new Promise((resolve, reject) => {
    console.log('pending'); // pending...
    reject(new Error(`I'm Error Rejected`));
  })
    .then(a => console.log(res))
    .catch(err => console.log(err));

promise(); // Error: I'm Error Rejected
```

Callback hell 을 Promise로

```jsx
const a = () => {
  return new Promise((resolve, reject) => {
    resolve('resolveA');
    reject(new Error('ErrorA'));
  })
    .then(res => console.log(res))
    .catch(err => console.log(err));
};
const b = () => {
  return new Promise((resolve, reject) => {
    resolve('resolveB');
    reject(new Error('ErrorB'));
  })
    .then(res => console.log(res))
    .catch(err => console.log(err));
};
const c = () => {
  return new Promise((resolve, reject) => {
    resolve('resolveC');
    reject(new Error('ErrorC'));
  })
    .then(res => console.log(res))
    .catch(err => console.log(err));
};
const d = () => {
  return new Promise((resolve, reject) => {
    resolve('resolveD');
    reject(new Error('ErrorD'));
  });
};
const e = () => {
  return new Promise((resolve, reject) => {
    // resolve('resolveE'); 에러처리
    reject(new Error('ErrorE'));
  })
    .then(res => console.log(res))
    .catch(err => console.log(err));
};
const f = () => {
  return new Promise((resolve, reject) => {
    resolve('resolveF');
    reject(new Error('ErrorF'));
  })
    .then(res => console.log(res))
    .catch(err => console.log(err));
};

const promise = new Promise((resolve, reject) => {
  resolve('resolve');
  reject('reject');
})
  .then(res => console.log(res))
  .catch(err => console.log(err));

promise
  .then(a)
  .then(b)
  .then(c)
  .then(d)
  .then(e)
  .then(f)
  .catch(err => console.log(err));
/*
resolve
resolveA
resolveB
resolveC
Error: ErrorE
resolveF
*/
```

Promise를 사용하여 Callback Hell을 then 과 catch로 가독성을 높이고 에러처리를 쉽게 할 수 있다.

하지만 현재 Promise 객체를 쓰는 것보다 async/await이 훨씬더 가독성과 에러처리에 좋다.

## Promise 기반 async/await

`ES2017`에 새로 추가된 `async/await`는 위에서 알아봤던 `Promise 객체`를 기반으로 사용한다.

함수 앞에 async만 붙이면 Promise 객체가 된다

```jsx
const a = () => {
  console.log('a');
};
const b = () => {
  console.log('b');
};
const c = () => {
  console.log('c');
};
const d = () => {
  console.log('d');
};
const e = () => {
  throw new Error('e');
};
const f = () => {
  console.log('f');
};

const AsyncAwaitFunc = async () => {
  console.log('start');
  try {
    await a();
    await b();
    await c();
    await d();
    await e();
    await f();
  } catch (err) {
    console.log(err);
  }
  console.log('end');
};

AsyncAwaitFunc();
/*
start
a
b
c
d
(node:2243) UnhandledPromiseRejectionWarning: Error: e
*/
```

try catch 문과 함께 사용하면 가독성과 에러처리를 손쉽게 할 수 있다.

비동기 처리는 async await를 사용하여 더 클린한 코드를 작성하도록 하는게 좋겠다 생각이 든다.

## 참고

- 모던 자바스크립트 Deep Dive - 이웅모
